spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/war2384/config-repo
          username: war2384
          password: 19880907er
          basedir: /Users/weiyuhang/IdeaProjects/imooc/config/target/basedir
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
